### ISSUE TITLE
Wrong use of node-fetch in eval

### ISSUE THREAD

**Issue by ionadev** [Omni-Discord-Bot/OmniBot#3]
# Wrong Use Of `node-fetch` in eval command

* The node-fetch module exports only one function. In The Eval Command, it had been imported wrongly. - https://github.com/Omni-Discord-Bot/OmniBot/blob/fea4501447c710ba255beeb0492e0c580993c2ee/commands/Admin/eval.js#L3

* Also, this is not how we post using node-fetch and get results - https://github.com/Omni-Discord-Bot/OmniBot/blob/fea4501447c710ba255beeb0492e0c580993c2ee/commands/Admin/eval.js#L130

**Comment by Phunt05** [comment]
Yea it was snekfetch and i imported node-fetch as snekfetch is deprecated, but i forgot to change the codes. Will change codes later. I have imported snekfetch for now.

**Comment by Anish-Shobith** [comment]
Ehh

**Comment by ionadev** [comment]
:fp:
